# Generated by Django 4.2.1 on 2023-05-10 08:07

import django.contrib.postgres.fields
from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attendee', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120, null=True), blank=True, null=True, size=None)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attendee', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120, null=True), blank=True, null=True, size=None)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=120, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
